# -*- coding: utf-8 -*-
"""Sharp-PATE_mnist_privacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNpR4FqVQRGC1dg4cIdO_pgVp0_GKFCK

## Performing PATE Analysis on the student labels generated by the Aggregated Teacher
"""

# All PATE variants have almost the same epsilon-delta values. Therefore, in this file we perform privacy analysis on Sharp-PATE(both)

# Steps to install syft package:
# 1) Run the command 'pip install syft==0.2.9' to install syft package
# 2) Restart the runtime after installation
# 3) Comment the command 'pip install syft==0.2.9' after installation

# pip install syft==0.2.9

from syft.frameworks.torch.dp import pate
import numpy as np

noise = 0.18025
delta = 1e-5

#loading saved files
pred_load = np.loadtxt('saved_privacy_logs/predictions_mnist.txt', dtype=int)
student_labels_load = np.loadtxt('saved_privacy_logs/student_labels_mnist.txt', dtype=int)

data_dep_eps, data_ind_eps = pate.perform_analysis(teacher_preds=pred_load, indices=student_labels_load, noise_eps=noise, delta=delta)
print("Epsilon-delta privacy:")
print("\u03B5-\u03B4 privacy: ({:.5f}, {})".format(data_dep_eps, delta))